/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as KayttoehdotRouteImport } from './routes/kayttoehdot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PalauteRouteImport } from './routes/palaute'
import { Route as RekisteroidyRouteImport } from './routes/rekisteroidy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TietosuojaRouteImport } from './routes/tietosuoja'
import { Route as UkkRouteImport } from './routes/ukk'
import { Route as UnohtunutSalasanaRouteImport } from './routes/unohtunut-salasana'
import { Route as VaihdaSalasanaRouteImport } from './routes/vaihda-salasana'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHuoltohistoriaRouteImport } from './routes/_authenticated/huoltohistoria'
import { Route as AuthenticatedKotitalousvahennysRouteImport } from './routes/_authenticated/kotitalousvahennys'
import { Route as AuthenticatedKulutRouteImport } from './routes/_authenticated/kulut'
import { Route as AuthenticatedMyyntiraporttiRouteImport } from './routes/_authenticated/myyntiraportti'
import { Route as AuthenticatedPtsRouteImport } from './routes/_authenticated/pts'
import { Route as AuthenticatedPyynnotRouteImport } from './routes/_authenticated/pyynnot'
import { Route as AuthenticatedTalonTiedotRouteImport } from './routes/_authenticated/talon-tiedot'
import { Route as AuthenticatedVuosikelloRouteImport } from './routes/_authenticated/vuosikello'
import { Route as BlogiSahkoinenTalokirjaRouteImport } from './routes/blogi/sahkoinen-talokirja'
import { Route as ApiPublicPalauteRouteImport } from './routes/api/public/palaute'
import { Route as ApiPublicHooksKausikirjeFollowupRouteImport } from './routes/api/public/hooks/kausikirje-followup'
import { Route as ApiPublicHooksLahetaKausikirjeRouteImport } from './routes/api/public/hooks/laheta-kausikirje'
import { Route as ApiPublicHooksLiidiAamukoontiRouteImport } from './routes/api/public/hooks/liidi-aamukoonti'
import { Route as ApiPublicHooksNuohousMuistutusRouteImport } from './routes/api/public/hooks/nuohous-muistutus'
import { Route as ApiPublicHooksYdinprosessiEskalointiRouteImport } from './routes/api/public/hooks/ydinprosessi-eskalointi'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const KayttoehdotRoute = KayttoehdotRouteImport.update({
  id: '/kayttoehdot',
  path: '/kayttoehdot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PalauteRoute = PalauteRouteImport.update({
  id: '/palaute',
  path: '/palaute',
  getParentRoute: () => rootRouteImport,
} as any)
const RekisteroidyRoute = RekisteroidyRouteImport.update({
  id: '/rekisteroidy',
  path: '/rekisteroidy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TietosuojaRoute = TietosuojaRouteImport.update({
  id: '/tietosuoja',
  path: '/tietosuoja',
  getParentRoute: () => rootRouteImport,
} as any)
const UkkRoute = UkkRouteImport.update({
  id: '/ukk',
  path: '/ukk',
  getParentRoute: () => rootRouteImport,
} as any)
const UnohtunutSalasanaRoute = UnohtunutSalasanaRouteImport.update({
  id: '/unohtunut-salasana',
  path: '/unohtunut-salasana',
  getParentRoute: () => rootRouteImport,
} as any)
const VaihdaSalasanaRoute = VaihdaSalasanaRouteImport.update({
  id: '/vaihda-salasana',
  path: '/vaihda-salasana',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHuoltohistoriaRoute =
  AuthenticatedHuoltohistoriaRouteImport.update({
    id: '/huoltohistoria',
    path: '/huoltohistoria',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKotitalousvahennysRoute =
  AuthenticatedKotitalousvahennysRouteImport.update({
    id: '/kotitalousvahennys',
    path: '/kotitalousvahennys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKulutRoute = AuthenticatedKulutRouteImport.update({
  id: '/kulut',
  path: '/kulut',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyyntiraporttiRoute =
  AuthenticatedMyyntiraporttiRouteImport.update({
    id: '/myyntiraportti',
    path: '/myyntiraportti',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPtsRoute = AuthenticatedPtsRouteImport.update({
  id: '/pts',
  path: '/pts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPyynnotRoute = AuthenticatedPyynnotRouteImport.update({
  id: '/pyynnot',
  path: '/pyynnot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTalonTiedotRoute =
  AuthenticatedTalonTiedotRouteImport.update({
    id: '/talon-tiedot',
    path: '/talon-tiedot',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVuosikelloRoute = AuthenticatedVuosikelloRouteImport.update({
  id: '/vuosikello',
  path: '/vuosikello',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BlogiSahkoinenTalokirjaRoute = BlogiSahkoinenTalokirjaRouteImport.update({
  id: '/blogi/sahkoinen-talokirja',
  path: '/blogi/sahkoinen-talokirja',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPalauteRoute = ApiPublicPalauteRouteImport.update({
  id: '/api/public/palaute',
  path: '/api/public/palaute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksKausikirjeFollowupRoute =
  ApiPublicHooksKausikirjeFollowupRouteImport.update({
    id: '/api/public/hooks/kausikirje-followup',
    path: '/api/public/hooks/kausikirje-followup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLahetaKausikirjeRoute =
  ApiPublicHooksLahetaKausikirjeRouteImport.update({
    id: '/api/public/hooks/laheta-kausikirje',
    path: '/api/public/hooks/laheta-kausikirje',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLiidiAamukoontiRoute =
  ApiPublicHooksLiidiAamukoontiRouteImport.update({
    id: '/api/public/hooks/liidi-aamukoonti',
    path: '/api/public/hooks/liidi-aamukoonti',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNuohousMuistutusRoute =
  ApiPublicHooksNuohousMuistutusRouteImport.update({
    id: '/api/public/hooks/nuohous-muistutus',
    path: '/api/public/hooks/nuohous-muistutus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksYdinprosessiEskalointiRoute =
  ApiPublicHooksYdinprosessiEskalointiRouteImport.update({
    id: '/api/public/hooks/ydinprosessi-eskalointi',
    path: '/api/public/hooks/ydinprosessi-eskalointi',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/login': typeof LoginRoute
  '/palaute': typeof PalauteRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/ukk': typeof UkkRoute
  '/unohtunut-salasana': typeof UnohtunutSalasanaRoute
  '/vaihda-salasana': typeof VaihdaSalasanaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/huoltohistoria': typeof AuthenticatedHuoltohistoriaRoute
  '/kotitalousvahennys': typeof AuthenticatedKotitalousvahennysRoute
  '/kulut': typeof AuthenticatedKulutRoute
  '/myyntiraportti': typeof AuthenticatedMyyntiraporttiRoute
  '/pts': typeof AuthenticatedPtsRoute
  '/pyynnot': typeof AuthenticatedPyynnotRoute
  '/talon-tiedot': typeof AuthenticatedTalonTiedotRoute
  '/vuosikello': typeof AuthenticatedVuosikelloRoute
  '/blogi/sahkoinen-talokirja': typeof BlogiSahkoinenTalokirjaRoute
  '/api/public/palaute': typeof ApiPublicPalauteRoute
  '/api/public/hooks/kausikirje-followup': typeof ApiPublicHooksKausikirjeFollowupRoute
  '/api/public/hooks/laheta-kausikirje': typeof ApiPublicHooksLahetaKausikirjeRoute
  '/api/public/hooks/liidi-aamukoonti': typeof ApiPublicHooksLiidiAamukoontiRoute
  '/api/public/hooks/nuohous-muistutus': typeof ApiPublicHooksNuohousMuistutusRoute
  '/api/public/hooks/ydinprosessi-eskalointi': typeof ApiPublicHooksYdinprosessiEskalointiRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/login': typeof LoginRoute
  '/palaute': typeof PalauteRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/ukk': typeof UkkRoute
  '/unohtunut-salasana': typeof UnohtunutSalasanaRoute
  '/vaihda-salasana': typeof VaihdaSalasanaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/huoltohistoria': typeof AuthenticatedHuoltohistoriaRoute
  '/kotitalousvahennys': typeof AuthenticatedKotitalousvahennysRoute
  '/kulut': typeof AuthenticatedKulutRoute
  '/myyntiraportti': typeof AuthenticatedMyyntiraporttiRoute
  '/pts': typeof AuthenticatedPtsRoute
  '/pyynnot': typeof AuthenticatedPyynnotRoute
  '/talon-tiedot': typeof AuthenticatedTalonTiedotRoute
  '/vuosikello': typeof AuthenticatedVuosikelloRoute
  '/blogi/sahkoinen-talokirja': typeof BlogiSahkoinenTalokirjaRoute
  '/api/public/palaute': typeof ApiPublicPalauteRoute
  '/api/public/hooks/kausikirje-followup': typeof ApiPublicHooksKausikirjeFollowupRoute
  '/api/public/hooks/laheta-kausikirje': typeof ApiPublicHooksLahetaKausikirjeRoute
  '/api/public/hooks/liidi-aamukoonti': typeof ApiPublicHooksLiidiAamukoontiRoute
  '/api/public/hooks/nuohous-muistutus': typeof ApiPublicHooksNuohousMuistutusRoute
  '/api/public/hooks/ydinprosessi-eskalointi': typeof ApiPublicHooksYdinprosessiEskalointiRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/kayttoehdot': typeof KayttoehdotRoute
  '/login': typeof LoginRoute
  '/palaute': typeof PalauteRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/ukk': typeof UkkRoute
  '/unohtunut-salasana': typeof UnohtunutSalasanaRoute
  '/vaihda-salasana': typeof VaihdaSalasanaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/huoltohistoria': typeof AuthenticatedHuoltohistoriaRoute
  '/_authenticated/kotitalousvahennys': typeof AuthenticatedKotitalousvahennysRoute
  '/_authenticated/kulut': typeof AuthenticatedKulutRoute
  '/_authenticated/myyntiraportti': typeof AuthenticatedMyyntiraporttiRoute
  '/_authenticated/pts': typeof AuthenticatedPtsRoute
  '/_authenticated/pyynnot': typeof AuthenticatedPyynnotRoute
  '/_authenticated/talon-tiedot': typeof AuthenticatedTalonTiedotRoute
  '/_authenticated/vuosikello': typeof AuthenticatedVuosikelloRoute
  '/blogi/sahkoinen-talokirja': typeof BlogiSahkoinenTalokirjaRoute
  '/api/public/palaute': typeof ApiPublicPalauteRoute
  '/api/public/hooks/kausikirje-followup': typeof ApiPublicHooksKausikirjeFollowupRoute
  '/api/public/hooks/laheta-kausikirje': typeof ApiPublicHooksLahetaKausikirjeRoute
  '/api/public/hooks/liidi-aamukoonti': typeof ApiPublicHooksLiidiAamukoontiRoute
  '/api/public/hooks/nuohous-muistutus': typeof ApiPublicHooksNuohousMuistutusRoute
  '/api/public/hooks/ydinprosessi-eskalointi': typeof ApiPublicHooksYdinprosessiEskalointiRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kayttoehdot'
    | '/login'
    | '/palaute'
    | '/rekisteroidy'
    | '/sitemap.xml'
    | '/tietosuoja'
    | '/ukk'
    | '/unohtunut-salasana'
    | '/vaihda-salasana'
    | '/admin'
    | '/dashboard'
    | '/huoltohistoria'
    | '/kotitalousvahennys'
    | '/kulut'
    | '/myyntiraportti'
    | '/pts'
    | '/pyynnot'
    | '/talon-tiedot'
    | '/vuosikello'
    | '/blogi/sahkoinen-talokirja'
    | '/api/public/palaute'
    | '/api/public/hooks/kausikirje-followup'
    | '/api/public/hooks/laheta-kausikirje'
    | '/api/public/hooks/liidi-aamukoonti'
    | '/api/public/hooks/nuohous-muistutus'
    | '/api/public/hooks/ydinprosessi-eskalointi'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kayttoehdot'
    | '/login'
    | '/palaute'
    | '/rekisteroidy'
    | '/sitemap.xml'
    | '/tietosuoja'
    | '/ukk'
    | '/unohtunut-salasana'
    | '/vaihda-salasana'
    | '/admin'
    | '/dashboard'
    | '/huoltohistoria'
    | '/kotitalousvahennys'
    | '/kulut'
    | '/myyntiraportti'
    | '/pts'
    | '/pyynnot'
    | '/talon-tiedot'
    | '/vuosikello'
    | '/blogi/sahkoinen-talokirja'
    | '/api/public/palaute'
    | '/api/public/hooks/kausikirje-followup'
    | '/api/public/hooks/laheta-kausikirje'
    | '/api/public/hooks/liidi-aamukoonti'
    | '/api/public/hooks/nuohous-muistutus'
    | '/api/public/hooks/ydinprosessi-eskalointi'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/kayttoehdot'
    | '/login'
    | '/palaute'
    | '/rekisteroidy'
    | '/sitemap.xml'
    | '/tietosuoja'
    | '/ukk'
    | '/unohtunut-salasana'
    | '/vaihda-salasana'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/huoltohistoria'
    | '/_authenticated/kotitalousvahennys'
    | '/_authenticated/kulut'
    | '/_authenticated/myyntiraportti'
    | '/_authenticated/pts'
    | '/_authenticated/pyynnot'
    | '/_authenticated/talon-tiedot'
    | '/_authenticated/vuosikello'
    | '/blogi/sahkoinen-talokirja'
    | '/api/public/palaute'
    | '/api/public/hooks/kausikirje-followup'
    | '/api/public/hooks/laheta-kausikirje'
    | '/api/public/hooks/liidi-aamukoonti'
    | '/api/public/hooks/nuohous-muistutus'
    | '/api/public/hooks/ydinprosessi-eskalointi'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  KayttoehdotRoute: typeof KayttoehdotRoute
  LoginRoute: typeof LoginRoute
  PalauteRoute: typeof PalauteRoute
  RekisteroidyRoute: typeof RekisteroidyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TietosuojaRoute: typeof TietosuojaRoute
  UkkRoute: typeof UkkRoute
  UnohtunutSalasanaRoute: typeof UnohtunutSalasanaRoute
  VaihdaSalasanaRoute: typeof VaihdaSalasanaRoute
  BlogiSahkoinenTalokirjaRoute: typeof BlogiSahkoinenTalokirjaRoute
  ApiPublicPalauteRoute: typeof ApiPublicPalauteRoute
  ApiPublicHooksKausikirjeFollowupRoute: typeof ApiPublicHooksKausikirjeFollowupRoute
  ApiPublicHooksLahetaKausikirjeRoute: typeof ApiPublicHooksLahetaKausikirjeRoute
  ApiPublicHooksLiidiAamukoontiRoute: typeof ApiPublicHooksLiidiAamukoontiRoute
  ApiPublicHooksNuohousMuistutusRoute: typeof ApiPublicHooksNuohousMuistutusRoute
  ApiPublicHooksYdinprosessiEskalointiRoute: typeof ApiPublicHooksYdinprosessiEskalointiRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayttoehdot': {
      id: '/kayttoehdot'
      path: '/kayttoehdot'
      fullPath: '/kayttoehdot'
      preLoaderRoute: typeof KayttoehdotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palaute': {
      id: '/palaute'
      path: '/palaute'
      fullPath: '/palaute'
      preLoaderRoute: typeof PalauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekisteroidy': {
      id: '/rekisteroidy'
      path: '/rekisteroidy'
      fullPath: '/rekisteroidy'
      preLoaderRoute: typeof RekisteroidyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tietosuoja': {
      id: '/tietosuoja'
      path: '/tietosuoja'
      fullPath: '/tietosuoja'
      preLoaderRoute: typeof TietosuojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukk': {
      id: '/ukk'
      path: '/ukk'
      fullPath: '/ukk'
      preLoaderRoute: typeof UkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unohtunut-salasana': {
      id: '/unohtunut-salasana'
      path: '/unohtunut-salasana'
      fullPath: '/unohtunut-salasana'
      preLoaderRoute: typeof UnohtunutSalasanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaihda-salasana': {
      id: '/vaihda-salasana'
      path: '/vaihda-salasana'
      fullPath: '/vaihda-salasana'
      preLoaderRoute: typeof VaihdaSalasanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/huoltohistoria': {
      id: '/_authenticated/huoltohistoria'
      path: '/huoltohistoria'
      fullPath: '/huoltohistoria'
      preLoaderRoute: typeof AuthenticatedHuoltohistoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kotitalousvahennys': {
      id: '/_authenticated/kotitalousvahennys'
      path: '/kotitalousvahennys'
      fullPath: '/kotitalousvahennys'
      preLoaderRoute: typeof AuthenticatedKotitalousvahennysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kulut': {
      id: '/_authenticated/kulut'
      path: '/kulut'
      fullPath: '/kulut'
      preLoaderRoute: typeof AuthenticatedKulutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/myyntiraportti': {
      id: '/_authenticated/myyntiraportti'
      path: '/myyntiraportti'
      fullPath: '/myyntiraportti'
      preLoaderRoute: typeof AuthenticatedMyyntiraporttiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pts': {
      id: '/_authenticated/pts'
      path: '/pts'
      fullPath: '/pts'
      preLoaderRoute: typeof AuthenticatedPtsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pyynnot': {
      id: '/_authenticated/pyynnot'
      path: '/pyynnot'
      fullPath: '/pyynnot'
      preLoaderRoute: typeof AuthenticatedPyynnotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/talon-tiedot': {
      id: '/_authenticated/talon-tiedot'
      path: '/talon-tiedot'
      fullPath: '/talon-tiedot'
      preLoaderRoute: typeof AuthenticatedTalonTiedotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vuosikello': {
      id: '/_authenticated/vuosikello'
      path: '/vuosikello'
      fullPath: '/vuosikello'
      preLoaderRoute: typeof AuthenticatedVuosikelloRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/blogi/sahkoinen-talokirja': {
      id: '/blogi/sahkoinen-talokirja'
      path: '/blogi/sahkoinen-talokirja'
      fullPath: '/blogi/sahkoinen-talokirja'
      preLoaderRoute: typeof BlogiSahkoinenTalokirjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/palaute': {
      id: '/api/public/palaute'
      path: '/api/public/palaute'
      fullPath: '/api/public/palaute'
      preLoaderRoute: typeof ApiPublicPalauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/kausikirje-followup': {
      id: '/api/public/hooks/kausikirje-followup'
      path: '/api/public/hooks/kausikirje-followup'
      fullPath: '/api/public/hooks/kausikirje-followup'
      preLoaderRoute: typeof ApiPublicHooksKausikirjeFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/laheta-kausikirje': {
      id: '/api/public/hooks/laheta-kausikirje'
      path: '/api/public/hooks/laheta-kausikirje'
      fullPath: '/api/public/hooks/laheta-kausikirje'
      preLoaderRoute: typeof ApiPublicHooksLahetaKausikirjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/liidi-aamukoonti': {
      id: '/api/public/hooks/liidi-aamukoonti'
      path: '/api/public/hooks/liidi-aamukoonti'
      fullPath: '/api/public/hooks/liidi-aamukoonti'
      preLoaderRoute: typeof ApiPublicHooksLiidiAamukoontiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nuohous-muistutus': {
      id: '/api/public/hooks/nuohous-muistutus'
      path: '/api/public/hooks/nuohous-muistutus'
      fullPath: '/api/public/hooks/nuohous-muistutus'
      preLoaderRoute: typeof ApiPublicHooksNuohousMuistutusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ydinprosessi-eskalointi': {
      id: '/api/public/hooks/ydinprosessi-eskalointi'
      path: '/api/public/hooks/ydinprosessi-eskalointi'
      fullPath: '/api/public/hooks/ydinprosessi-eskalointi'
      preLoaderRoute: typeof ApiPublicHooksYdinprosessiEskalointiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHuoltohistoriaRoute: typeof AuthenticatedHuoltohistoriaRoute
  AuthenticatedKotitalousvahennysRoute: typeof AuthenticatedKotitalousvahennysRoute
  AuthenticatedKulutRoute: typeof AuthenticatedKulutRoute
  AuthenticatedMyyntiraporttiRoute: typeof AuthenticatedMyyntiraporttiRoute
  AuthenticatedPtsRoute: typeof AuthenticatedPtsRoute
  AuthenticatedPyynnotRoute: typeof AuthenticatedPyynnotRoute
  AuthenticatedTalonTiedotRoute: typeof AuthenticatedTalonTiedotRoute
  AuthenticatedVuosikelloRoute: typeof AuthenticatedVuosikelloRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHuoltohistoriaRoute: AuthenticatedHuoltohistoriaRoute,
  AuthenticatedKotitalousvahennysRoute: AuthenticatedKotitalousvahennysRoute,
  AuthenticatedKulutRoute: AuthenticatedKulutRoute,
  AuthenticatedMyyntiraporttiRoute: AuthenticatedMyyntiraporttiRoute,
  AuthenticatedPtsRoute: AuthenticatedPtsRoute,
  AuthenticatedPyynnotRoute: AuthenticatedPyynnotRoute,
  AuthenticatedTalonTiedotRoute: AuthenticatedTalonTiedotRoute,
  AuthenticatedVuosikelloRoute: AuthenticatedVuosikelloRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  KayttoehdotRoute: KayttoehdotRoute,
  LoginRoute: LoginRoute,
  PalauteRoute: PalauteRoute,
  RekisteroidyRoute: RekisteroidyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TietosuojaRoute: TietosuojaRoute,
  UkkRoute: UkkRoute,
  UnohtunutSalasanaRoute: UnohtunutSalasanaRoute,
  VaihdaSalasanaRoute: VaihdaSalasanaRoute,
  BlogiSahkoinenTalokirjaRoute: BlogiSahkoinenTalokirjaRoute,
  ApiPublicPalauteRoute: ApiPublicPalauteRoute,
  ApiPublicHooksKausikirjeFollowupRoute: ApiPublicHooksKausikirjeFollowupRoute,
  ApiPublicHooksLahetaKausikirjeRoute: ApiPublicHooksLahetaKausikirjeRoute,
  ApiPublicHooksLiidiAamukoontiRoute: ApiPublicHooksLiidiAamukoontiRoute,
  ApiPublicHooksNuohousMuistutusRoute: ApiPublicHooksNuohousMuistutusRoute,
  ApiPublicHooksYdinprosessiEskalointiRoute:
    ApiPublicHooksYdinprosessiEskalointiRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
