/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaihdaSalasanaRouteImport } from './routes/vaihda-salasana'
import { Route as UnohtunutSalasanaRouteImport } from './routes/unohtunut-salasana'
import { Route as UkkRouteImport } from './routes/ukk'
import { Route as TietosuojaRouteImport } from './routes/tietosuoja'
import { Route as RekisteroidyRouteImport } from './routes/rekisteroidy'
import { Route as PalauteRouteImport } from './routes/palaute'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KayttoehdotRouteImport } from './routes/kayttoehdot'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpasIndexRouteImport } from './routes/opas/index'
import { Route as OpasNuohousHintaRouteImport } from './routes/opas/nuohous-hinta'
import { Route as OpasIvPuhdistusRouteImport } from './routes/opas/iv-puhdistus'
import { Route as AuthenticatedVuosikelloRouteImport } from './routes/_authenticated/vuosikello'
import { Route as AuthenticatedTalonTiedotRouteImport } from './routes/_authenticated/talon-tiedot'
import { Route as AuthenticatedPyynnotRouteImport } from './routes/_authenticated/pyynnot'
import { Route as AuthenticatedPtsRouteImport } from './routes/_authenticated/pts'
import { Route as AuthenticatedKulutRouteImport } from './routes/_authenticated/kulut'
import { Route as AuthenticatedHuoltohistoriaRouteImport } from './routes/_authenticated/huoltohistoria'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPalauteRouteImport } from './routes/api/public/palaute'
import { Route as ApiPublicHooksNuohousMuistutusRouteImport } from './routes/api/public/hooks/nuohous-muistutus'
import { Route as ApiPublicHooksLahetaKausikirjeRouteImport } from './routes/api/public/hooks/laheta-kausikirje'

const VaihdaSalasanaRoute = VaihdaSalasanaRouteImport.update({
  id: '/vaihda-salasana',
  path: '/vaihda-salasana',
  getParentRoute: () => rootRouteImport,
} as any)
const UnohtunutSalasanaRoute = UnohtunutSalasanaRouteImport.update({
  id: '/unohtunut-salasana',
  path: '/unohtunut-salasana',
  getParentRoute: () => rootRouteImport,
} as any)
const UkkRoute = UkkRouteImport.update({
  id: '/ukk',
  path: '/ukk',
  getParentRoute: () => rootRouteImport,
} as any)
const TietosuojaRoute = TietosuojaRouteImport.update({
  id: '/tietosuoja',
  path: '/tietosuoja',
  getParentRoute: () => rootRouteImport,
} as any)
const RekisteroidyRoute = RekisteroidyRouteImport.update({
  id: '/rekisteroidy',
  path: '/rekisteroidy',
  getParentRoute: () => rootRouteImport,
} as any)
const PalauteRoute = PalauteRouteImport.update({
  id: '/palaute',
  path: '/palaute',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KayttoehdotRoute = KayttoehdotRouteImport.update({
  id: '/kayttoehdot',
  path: '/kayttoehdot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpasIndexRoute = OpasIndexRouteImport.update({
  id: '/opas/',
  path: '/opas/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpasNuohousHintaRoute = OpasNuohousHintaRouteImport.update({
  id: '/opas/nuohous-hinta',
  path: '/opas/nuohous-hinta',
  getParentRoute: () => rootRouteImport,
} as any)
const OpasIvPuhdistusRoute = OpasIvPuhdistusRouteImport.update({
  id: '/opas/iv-puhdistus',
  path: '/opas/iv-puhdistus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVuosikelloRoute = AuthenticatedVuosikelloRouteImport.update({
  id: '/vuosikello',
  path: '/vuosikello',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTalonTiedotRoute =
  AuthenticatedTalonTiedotRouteImport.update({
    id: '/talon-tiedot',
    path: '/talon-tiedot',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPyynnotRoute = AuthenticatedPyynnotRouteImport.update({
  id: '/pyynnot',
  path: '/pyynnot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPtsRoute = AuthenticatedPtsRouteImport.update({
  id: '/pts',
  path: '/pts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKulutRoute = AuthenticatedKulutRouteImport.update({
  id: '/kulut',
  path: '/kulut',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHuoltohistoriaRoute =
  AuthenticatedHuoltohistoriaRouteImport.update({
    id: '/huoltohistoria',
    path: '/huoltohistoria',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPalauteRoute = ApiPublicPalauteRouteImport.update({
  id: '/api/public/palaute',
  path: '/api/public/palaute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNuohousMuistutusRoute =
  ApiPublicHooksNuohousMuistutusRouteImport.update({
    id: '/api/public/hooks/nuohous-muistutus',
    path: '/api/public/hooks/nuohous-muistutus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLahetaKausikirjeRoute =
  ApiPublicHooksLahetaKausikirjeRouteImport.update({
    id: '/api/public/hooks/laheta-kausikirje',
    path: '/api/public/hooks/laheta-kausikirje',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/login': typeof LoginRoute
  '/palaute': typeof PalauteRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/ukk': typeof UkkRoute
  '/unohtunut-salasana': typeof UnohtunutSalasanaRoute
  '/vaihda-salasana': typeof VaihdaSalasanaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/huoltohistoria': typeof AuthenticatedHuoltohistoriaRoute
  '/kulut': typeof AuthenticatedKulutRoute
  '/pts': typeof AuthenticatedPtsRoute
  '/pyynnot': typeof AuthenticatedPyynnotRoute
  '/talon-tiedot': typeof AuthenticatedTalonTiedotRoute
  '/vuosikello': typeof AuthenticatedVuosikelloRoute
  '/opas/iv-puhdistus': typeof OpasIvPuhdistusRoute
  '/opas/nuohous-hinta': typeof OpasNuohousHintaRoute
  '/opas/': typeof OpasIndexRoute
  '/api/public/palaute': typeof ApiPublicPalauteRoute
  '/api/public/hooks/laheta-kausikirje': typeof ApiPublicHooksLahetaKausikirjeRoute
  '/api/public/hooks/nuohous-muistutus': typeof ApiPublicHooksNuohousMuistutusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/login': typeof LoginRoute
  '/palaute': typeof PalauteRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/ukk': typeof UkkRoute
  '/unohtunut-salasana': typeof UnohtunutSalasanaRoute
  '/vaihda-salasana': typeof VaihdaSalasanaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/huoltohistoria': typeof AuthenticatedHuoltohistoriaRoute
  '/kulut': typeof AuthenticatedKulutRoute
  '/pts': typeof AuthenticatedPtsRoute
  '/pyynnot': typeof AuthenticatedPyynnotRoute
  '/talon-tiedot': typeof AuthenticatedTalonTiedotRoute
  '/vuosikello': typeof AuthenticatedVuosikelloRoute
  '/opas/iv-puhdistus': typeof OpasIvPuhdistusRoute
  '/opas/nuohous-hinta': typeof OpasNuohousHintaRoute
  '/opas': typeof OpasIndexRoute
  '/api/public/palaute': typeof ApiPublicPalauteRoute
  '/api/public/hooks/laheta-kausikirje': typeof ApiPublicHooksLahetaKausikirjeRoute
  '/api/public/hooks/nuohous-muistutus': typeof ApiPublicHooksNuohousMuistutusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/kayttoehdot': typeof KayttoehdotRoute
  '/login': typeof LoginRoute
  '/palaute': typeof PalauteRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/ukk': typeof UkkRoute
  '/unohtunut-salasana': typeof UnohtunutSalasanaRoute
  '/vaihda-salasana': typeof VaihdaSalasanaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/huoltohistoria': typeof AuthenticatedHuoltohistoriaRoute
  '/_authenticated/kulut': typeof AuthenticatedKulutRoute
  '/_authenticated/pts': typeof AuthenticatedPtsRoute
  '/_authenticated/pyynnot': typeof AuthenticatedPyynnotRoute
  '/_authenticated/talon-tiedot': typeof AuthenticatedTalonTiedotRoute
  '/_authenticated/vuosikello': typeof AuthenticatedVuosikelloRoute
  '/opas/iv-puhdistus': typeof OpasIvPuhdistusRoute
  '/opas/nuohous-hinta': typeof OpasNuohousHintaRoute
  '/opas/': typeof OpasIndexRoute
  '/api/public/palaute': typeof ApiPublicPalauteRoute
  '/api/public/hooks/laheta-kausikirje': typeof ApiPublicHooksLahetaKausikirjeRoute
  '/api/public/hooks/nuohous-muistutus': typeof ApiPublicHooksNuohousMuistutusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kayttoehdot'
    | '/login'
    | '/palaute'
    | '/rekisteroidy'
    | '/tietosuoja'
    | '/ukk'
    | '/unohtunut-salasana'
    | '/vaihda-salasana'
    | '/admin'
    | '/dashboard'
    | '/huoltohistoria'
    | '/kulut'
    | '/pts'
    | '/pyynnot'
    | '/talon-tiedot'
    | '/vuosikello'
    | '/opas/iv-puhdistus'
    | '/opas/nuohous-hinta'
    | '/opas/'
    | '/api/public/palaute'
    | '/api/public/hooks/laheta-kausikirje'
    | '/api/public/hooks/nuohous-muistutus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kayttoehdot'
    | '/login'
    | '/palaute'
    | '/rekisteroidy'
    | '/tietosuoja'
    | '/ukk'
    | '/unohtunut-salasana'
    | '/vaihda-salasana'
    | '/admin'
    | '/dashboard'
    | '/huoltohistoria'
    | '/kulut'
    | '/pts'
    | '/pyynnot'
    | '/talon-tiedot'
    | '/vuosikello'
    | '/opas/iv-puhdistus'
    | '/opas/nuohous-hinta'
    | '/opas'
    | '/api/public/palaute'
    | '/api/public/hooks/laheta-kausikirje'
    | '/api/public/hooks/nuohous-muistutus'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/kayttoehdot'
    | '/login'
    | '/palaute'
    | '/rekisteroidy'
    | '/tietosuoja'
    | '/ukk'
    | '/unohtunut-salasana'
    | '/vaihda-salasana'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/huoltohistoria'
    | '/_authenticated/kulut'
    | '/_authenticated/pts'
    | '/_authenticated/pyynnot'
    | '/_authenticated/talon-tiedot'
    | '/_authenticated/vuosikello'
    | '/opas/iv-puhdistus'
    | '/opas/nuohous-hinta'
    | '/opas/'
    | '/api/public/palaute'
    | '/api/public/hooks/laheta-kausikirje'
    | '/api/public/hooks/nuohous-muistutus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  KayttoehdotRoute: typeof KayttoehdotRoute
  LoginRoute: typeof LoginRoute
  PalauteRoute: typeof PalauteRoute
  RekisteroidyRoute: typeof RekisteroidyRoute
  TietosuojaRoute: typeof TietosuojaRoute
  UkkRoute: typeof UkkRoute
  UnohtunutSalasanaRoute: typeof UnohtunutSalasanaRoute
  VaihdaSalasanaRoute: typeof VaihdaSalasanaRoute
  OpasIvPuhdistusRoute: typeof OpasIvPuhdistusRoute
  OpasNuohousHintaRoute: typeof OpasNuohousHintaRoute
  OpasIndexRoute: typeof OpasIndexRoute
  ApiPublicPalauteRoute: typeof ApiPublicPalauteRoute
  ApiPublicHooksLahetaKausikirjeRoute: typeof ApiPublicHooksLahetaKausikirjeRoute
  ApiPublicHooksNuohousMuistutusRoute: typeof ApiPublicHooksNuohousMuistutusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaihda-salasana': {
      id: '/vaihda-salasana'
      path: '/vaihda-salasana'
      fullPath: '/vaihda-salasana'
      preLoaderRoute: typeof VaihdaSalasanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unohtunut-salasana': {
      id: '/unohtunut-salasana'
      path: '/unohtunut-salasana'
      fullPath: '/unohtunut-salasana'
      preLoaderRoute: typeof UnohtunutSalasanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukk': {
      id: '/ukk'
      path: '/ukk'
      fullPath: '/ukk'
      preLoaderRoute: typeof UkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tietosuoja': {
      id: '/tietosuoja'
      path: '/tietosuoja'
      fullPath: '/tietosuoja'
      preLoaderRoute: typeof TietosuojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekisteroidy': {
      id: '/rekisteroidy'
      path: '/rekisteroidy'
      fullPath: '/rekisteroidy'
      preLoaderRoute: typeof RekisteroidyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palaute': {
      id: '/palaute'
      path: '/palaute'
      fullPath: '/palaute'
      preLoaderRoute: typeof PalauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayttoehdot': {
      id: '/kayttoehdot'
      path: '/kayttoehdot'
      fullPath: '/kayttoehdot'
      preLoaderRoute: typeof KayttoehdotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opas/': {
      id: '/opas/'
      path: '/opas'
      fullPath: '/opas/'
      preLoaderRoute: typeof OpasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opas/nuohous-hinta': {
      id: '/opas/nuohous-hinta'
      path: '/opas/nuohous-hinta'
      fullPath: '/opas/nuohous-hinta'
      preLoaderRoute: typeof OpasNuohousHintaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opas/iv-puhdistus': {
      id: '/opas/iv-puhdistus'
      path: '/opas/iv-puhdistus'
      fullPath: '/opas/iv-puhdistus'
      preLoaderRoute: typeof OpasIvPuhdistusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vuosikello': {
      id: '/_authenticated/vuosikello'
      path: '/vuosikello'
      fullPath: '/vuosikello'
      preLoaderRoute: typeof AuthenticatedVuosikelloRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/talon-tiedot': {
      id: '/_authenticated/talon-tiedot'
      path: '/talon-tiedot'
      fullPath: '/talon-tiedot'
      preLoaderRoute: typeof AuthenticatedTalonTiedotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pyynnot': {
      id: '/_authenticated/pyynnot'
      path: '/pyynnot'
      fullPath: '/pyynnot'
      preLoaderRoute: typeof AuthenticatedPyynnotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pts': {
      id: '/_authenticated/pts'
      path: '/pts'
      fullPath: '/pts'
      preLoaderRoute: typeof AuthenticatedPtsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kulut': {
      id: '/_authenticated/kulut'
      path: '/kulut'
      fullPath: '/kulut'
      preLoaderRoute: typeof AuthenticatedKulutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/huoltohistoria': {
      id: '/_authenticated/huoltohistoria'
      path: '/huoltohistoria'
      fullPath: '/huoltohistoria'
      preLoaderRoute: typeof AuthenticatedHuoltohistoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/palaute': {
      id: '/api/public/palaute'
      path: '/api/public/palaute'
      fullPath: '/api/public/palaute'
      preLoaderRoute: typeof ApiPublicPalauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nuohous-muistutus': {
      id: '/api/public/hooks/nuohous-muistutus'
      path: '/api/public/hooks/nuohous-muistutus'
      fullPath: '/api/public/hooks/nuohous-muistutus'
      preLoaderRoute: typeof ApiPublicHooksNuohousMuistutusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/laheta-kausikirje': {
      id: '/api/public/hooks/laheta-kausikirje'
      path: '/api/public/hooks/laheta-kausikirje'
      fullPath: '/api/public/hooks/laheta-kausikirje'
      preLoaderRoute: typeof ApiPublicHooksLahetaKausikirjeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHuoltohistoriaRoute: typeof AuthenticatedHuoltohistoriaRoute
  AuthenticatedKulutRoute: typeof AuthenticatedKulutRoute
  AuthenticatedPtsRoute: typeof AuthenticatedPtsRoute
  AuthenticatedPyynnotRoute: typeof AuthenticatedPyynnotRoute
  AuthenticatedTalonTiedotRoute: typeof AuthenticatedTalonTiedotRoute
  AuthenticatedVuosikelloRoute: typeof AuthenticatedVuosikelloRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHuoltohistoriaRoute: AuthenticatedHuoltohistoriaRoute,
  AuthenticatedKulutRoute: AuthenticatedKulutRoute,
  AuthenticatedPtsRoute: AuthenticatedPtsRoute,
  AuthenticatedPyynnotRoute: AuthenticatedPyynnotRoute,
  AuthenticatedTalonTiedotRoute: AuthenticatedTalonTiedotRoute,
  AuthenticatedVuosikelloRoute: AuthenticatedVuosikelloRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  KayttoehdotRoute: KayttoehdotRoute,
  LoginRoute: LoginRoute,
  PalauteRoute: PalauteRoute,
  RekisteroidyRoute: RekisteroidyRoute,
  TietosuojaRoute: TietosuojaRoute,
  UkkRoute: UkkRoute,
  UnohtunutSalasanaRoute: UnohtunutSalasanaRoute,
  VaihdaSalasanaRoute: VaihdaSalasanaRoute,
  OpasIvPuhdistusRoute: OpasIvPuhdistusRoute,
  OpasNuohousHintaRoute: OpasNuohousHintaRoute,
  OpasIndexRoute: OpasIndexRoute,
  ApiPublicPalauteRoute: ApiPublicPalauteRoute,
  ApiPublicHooksLahetaKausikirjeRoute: ApiPublicHooksLahetaKausikirjeRoute,
  ApiPublicHooksNuohousMuistutusRoute: ApiPublicHooksNuohousMuistutusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
